services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:5001
    environment:
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    depends_on:
      - db
  db:
    image: docker.io/library/postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_DB}
    volumes:
    - db_data:/var/lib/postgresql/data

volumes:
db_data: {}